### ISSUE TITLE
[INFO][ILiveSDK] | ILiveRoom:Other_Procedure|onFirstFrameRecved|listener|not set

### ISSUE THREAD

**Issue by passerbycrk** [zhaoyang21cn/iLiveSDK_iOS_Suixinbo#27]
观众加入直播间成功，也添加了监听代码和回调方法，但是无法收到回调。
关键log如下：

``[INFO][ILiveSDK] | ILiveRoom:Other_Procedure|onFirstFrameRecved|listener|not set``

代码参考[ILiveSDK导入](https://github.com/zhaoyang21cn/iLiveSDK_iOS_Suixinbo/blob/master/ILiveSDK-README.md)实现，具体如下：

    // 1.init sdk
    // ...
    // 2.set listener
    TILLiveManager *manager = [TILLiveManager getInstance];
    [manager setAVListener:self];
    [manager setIMListener:self];
    // 3.join room
    ILiveRoomOption *option = [ILiveRoomOption defaultGuestLiveOption];
    option.controlRole = @"Guest";//配置角色
    [[ILiveRoomManager getInstance] joinRoom:_roomid option:option succ:^{
        NSLog(@"#TIL join room successed");
    } failed:^(NSString *module, int errId, NSString *errMsg) {
        NSLog(@"#TIL join room failed [%@(%@)] %@",module,@(errId),errMsg);
    }];
    // 4.ILVLiveAVListener
    - (void)onUserUpdateInfo:(ILVLiveAVEvent)event users:(NSArray *)users {
        for (NSString *user in users) {
            ILiveFrameDispatcher *frameDispatcher = [[ILiveRoomManager getInstance] getFrameDispatcher];
            UIView *containerView = [frameDispatcher addRenderAt:self.view.bounds
                                                   forIdentifier:user
                                                         srcType:QAVVIDEO_SRC_TYPE_CAMERA];
            [self.view addSubview:containerView];
            break;
        }
    }

    - (void)onFirstFrameRecved:(int)width height:(int)height identifier:(NSString *)identifier srcType:(avVideoSrcType)srcType {
        NSLog(@"#TIL onFirstFrameRecved:%@ height:%@ identifier:%@ srcType:%@",@(width),@(height),identifier,@(srcType));
    }

---

环境：

```
macOS Sierra 10.12.5 (16F73)
Xcode 8.3.3 (8E3004b)
```

|SDK|版本号|
|---|---|
|QAVSDK|1.9.1.17.OpenSDK_1.9.1-26127|
|IMSDK|v2.5.4.10421.10420|
|ILiveSDK|1.5.1.11058|
|TILLiveSDK|1.1.2|
|QAVEffect|--|
|TILFilterSDK|1.2.3|

**Comment by passerbycrk** [comment]
这么写可以收到onFirstFrameRecved的回调

    ILiveRoomOption *option = [ILiveRoomOption defaultGuestLiveOption]; 
    option.firstFrameListener = self;

但是我想在一个自定义Manager中统一处理Listenser，然后通过多重代理的方式代理给不同的ViewController或者View

**Comment by wilderliao1** [comment]
这里的接口不要调用混乱了：
1、TILLiveSDK的接口
	TILLiveRoomOption *option = [TILLiveRoomOption defaultHostLiveOption];
	[TILLiveManager getInstance] createRoom…..
	这个时候需要调用setAVListener这个接口

2、调用ILiveSDK的接口
	ILiveRoomOption *option = [ILiveRoomOption defaultHostLiveOption];//（注意，两个option类型不同）
	option.memberStatusListener = self;//不需要用setAvListener接口
	[ILiveRoomManager getInstance] createRoom….

上述接口只需要其中一套接口就可以了，建议用TILLiveSDK的接口

**Comment by wilderliao1** [comment]
加入房间也是同样的使用方法，不要用混了
